## To modify by developper(s) of the plugin

[plugin-info]
SHORT_PLUGIN_NAME = 'template'  #to be modified, for instance daqmx then rename the module name:
# (pymodaq_plugins_template become pymodaq_plugins_daqmx for instance)

package-url = 'https://github.com/PyMoDAQ/pymodaq_plugins_template' #to modify
description = 'some word about your plugin'

author = 'Author Name'
author-email = 'Author email'
license = 'MIT'

[plugin-install]
#packages required for your plugin:
packages-required = ['pymodaq>=4.0.0']
